// file generated by Big Pickle using OpenCode

import { describe, expect, test } from "bun:test";
import {
  addPlayer,
  removePlayer,
  createGame,
  joinGame,
  leaveGame,
  isPlayerInGame,
  generateGameId,
} from "../src/games";
import { ALREADY_IN_A_GAME, GAME_NOT_FOUND } from "@tour-de-mot/shared/error";
import type { Player } from "@tour-de-mot/shared/types";

const comparePlayers = (a: Player[], b: Player[]): boolean =>
  a.length === b.length &&
  a.every((p, i) => p.uuid === b[i]?.uuid && p.pseudo === b[i]?.pseudo);

const compareGames = (
  a: Map<string, Player[]>,
  b: Map<string, Player[]>,
): boolean => {
  if (a.size !== b.size) return false;
  for (const [key, players] of a) {
    const otherPlayers = b.get(key);
    if (!otherPlayers || !comparePlayers(players, otherPlayers)) return false;
  }
  return true;
};

describe("addPlayer", () => {
  const player: Player = { uuid: "123", pseudo: "Alice" };

  test("adds player to empty array", () => {
    const result = addPlayer([], player);
    expect(result).toHaveLength(1);
    expect(comparePlayers(result, [player])).toBe(true);
  });

  test("adds new player to existing array", () => {
    const players: Player[] = [{ uuid: "456", pseudo: "Bob" }];
    const result = addPlayer(players, player);
    expect(result).toHaveLength(2);
    expect(comparePlayers(result, [...players, player])).toBe(true);
  });

  test("does not add duplicate player", () => {
    const players: Player[] = [player];
    const result = addPlayer(players, player);
    expect(result).toHaveLength(1);
    expect(comparePlayers(result, players)).toBe(true);
  });
});

describe("removePlayer", () => {
  const player1: Player = { uuid: "123", pseudo: "Alice" };
  const player2: Player = { uuid: "456", pseudo: "Bob" };

  test("removes player by uuid", () => {
    const players: Player[] = [player1, player2];
    const result = removePlayer(players, "123");
    expect(result).toHaveLength(1);
    expect(comparePlayers(result, [player2])).toBe(true);
  });

  test("returns same array if uuid not found", () => {
    const players: Player[] = [player1];
    const result = removePlayer(players, "999");
    expect(result).toHaveLength(1);
    expect(comparePlayers(result, [player1])).toBe(true);
  });

  test("returns empty array when removing last player", () => {
    const result = removePlayer([player1], "123");
    expect(result).toHaveLength(0);
  });
});

describe("createGame", () => {
  const player: Player = { uuid: "123", pseudo: "Alice" };

  test("creates game with valid player", () => {
    const games = new Map<string, Player[]>();
    const result = createGame(games, player);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value).toHaveLength(6);
    expect(games.size).toBe(1);
    const gamePlayers = games.get(result.value);
    expect(gamePlayers).toHaveLength(1);
    expect(gamePlayers![0]).toEqual(player);
  });

  test("fails if player is already in a game", () => {
    const gameId = "EXISTIN";
    const games = new Map<string, Player[]>([[gameId, [player]]]);
    const result = createGame(games, player);

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toEqual(ALREADY_IN_A_GAME);
  });
});

describe("joinGame", () => {
  const player1: Player = { uuid: "123", pseudo: "Alice" };
  const player2: Player = { uuid: "456", pseudo: "Bob" };

  test("joins existing game", () => {
    const games = new Map<string, Player[]>([["GAME01", [player1]]]);
    const result = joinGame(games, "GAME01", player2);

    expect(result.ok).toBe(true);
    expect(games.get("GAME01")).toHaveLength(2);
  });

  test("fails if game not found", () => {
    const games = new Map<string, Player[]>();
    const result = joinGame(games, "GAME01", player1);

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toEqual(GAME_NOT_FOUND);
  });

  test("fails if player is already in the same game", () => {
    const games = new Map<string, Player[]>([["GAME01", [player1]]]);
    const result = joinGame(games, "GAME01", player1);

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toEqual(ALREADY_IN_A_GAME);
  });

  test("fails if player is already in a different game", () => {
    const games = new Map<string, Player[]>([
      ["GAME01", [player1]],
      ["GAME02", [player2]],
    ]);
    const result = joinGame(games, "GAME02", player1);

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toEqual(ALREADY_IN_A_GAME);
  });
});

describe("leaveGame", () => {
  const player1: Player = { uuid: "123", pseudo: "Alice" };
  const player2: Player = { uuid: "456", pseudo: "Bob" };

  test("removes player from game", () => {
    const games = new Map<string, Player[]>([["GAME01", [player1, player2]]]);
    const result = leaveGame(games, "GAME01", "123");

    expect(result.ok).toBe(true);
    expect(games.get("GAME01")).toHaveLength(1);
    expect(games.get("GAME01")![0]).toEqual(player2);
  });

  test("fails if game not found", () => {
    const games = new Map<string, Player[]>();
    const result = leaveGame(games, "GAME01", "123");

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toEqual(GAME_NOT_FOUND);
  });

  test("deletes game when last player leaves", () => {
    const games = new Map<string, Player[]>([["GAME01", [player1]]]);
    const result = leaveGame(games, "GAME01", "123");

    expect(result.ok).toBe(true);
    expect(games.has("GAME01")).toBe(false);
  });
});

describe("isPlayerInGame", () => {
  const player: Player = { uuid: "123", pseudo: "Alice" };

  test("returns true if player is in any game", () => {
    const games = new Map<string, Player[]>([["GAME1", [player]]]);
    expect(isPlayerInGame(games, player)).toBe(true);
  });

  test("returns true if player is in different game", () => {
    const games = new Map<string, Player[]>([
      ["GAME1", [{ uuid: "456", pseudo: "Bob" }]],
      ["GAME2", [player]],
    ]);
    expect(isPlayerInGame(games, player)).toBe(true);
  });

  test("returns false if player is not in any game", () => {
    const games = new Map<string, Player[]>([
      ["GAME1", [{ uuid: "456", pseudo: "Bob" }]],
    ]);
    expect(isPlayerInGame(games, player)).toBe(false);
  });

  test("returns false for empty games map", () => {
    const games = new Map<string, Player[]>();
    expect(isPlayerInGame(games, player)).toBe(false);
  });
});

describe("generateGameId", () => {
  test("generates id of default length 6", () => {
    const games = new Map<string, Player[]>();
    const id = generateGameId(games);
    expect(id).toHaveLength(6);
  });

  test("generates id with only valid characters", () => {
    const games = new Map<string, Player[]>();
    const id = generateGameId(games);
    const validChars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    expect(id.split("").every((c) => validChars.includes(c))).toBe(true);
  });

  test("respects custom length", () => {
    const games = new Map<string, Player[]>();
    const id = generateGameId(games, 8);
    expect(id).toHaveLength(8);
  });

  test("avoids collision with existing game ids", () => {
    const games = new Map<string, Player[]>([["EXIST01", []]]);
    const id = generateGameId(games);
    expect(games.has(id)).toBe(false);
  });
});
